name: Builder

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Build in Debian
        run: |
          docker run -v $PWD:/work -w /work debian:trixie bash -c '
            apt update
            mkdir -p pool/main
            for recipe in recipes/*.yml; do
              bash build-package.sh "$recipe"
            done
            apt install -y dpkg-dev
            mkdir -p dists/stable/main/binary-amd64
            cd dists/stable/main/binary-amd64
            dpkg-scanpackages ../../../../pool/main /dev/null > Packages
            gzip -k Packages
          '
      
      - uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
